[package]
name = "the-rooms"
version = "1.0.0"
edition = "2021"
description = "Short text-based adventure game."
readme = "README.md"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]